name:                mock-time
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/luntain/mock-time
license:             BSD3
author:              Kamil Dworakowski
maintainer:          example@example.com
copyright:           2020 Kamil Dworakowski
category:            Test
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - time
  - stm
  - mtl
  - exceptions
  - resourcet
  - primitive
  - unliftio-core
  - error-or
  - inbox

  - tasty
  - tasty-quickcheck
  - tasty-hunit
  - QuickCheck

library:
    source-dirs:      src

tests:
  my-test-suite:
    source-dirs: tests
    main: Tests.hs
    dependencies:
    - mock-time
    - error-or-utils
